[project]
name = "ansible-role-beszel"
version = "1.5.0"
description = "Ansible role to install and configure a Beszel binary agent."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "annotated-types==0.7.0",
    "ansible-builder==3.1.0",
    "ansible-compat==25.1.2",
    "ansible-core==2.18.2",
    "ansible-creator==25.0.0",
    "ansible-dev-environment==25.1.0",
    "ansible-dev-tools==25.2.0",
    "ansible-lint==25.1.2",
    "ansible-navigator==25.1.0",
    "ansible-runner==2.4.0",
    "ansible-sign==0.1.1",
    "attrs==25.1.0",
    "bindep==2.12.0",
    "black==25.1.0",
    "bracex==2.5.post1",
    "cachetools==5.5.1",
    "certifi==2025.1.31",
    "cffi==1.17.1",
    "cfgv==3.4.0",
    "chardet==5.2.0",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "click-help-colors==0.9.4",
    "colorama==0.4.6",
    "cryptography==44.0.1",
    "distlib==0.3.9",
    "distro==1.9.0",
    "docker==7.1.0",
    "enrich==1.2.7",
    "execnet==2.1.1",
    "filelock==3.17.0",
    "identify==2.6.7",
    "idna==3.10",
    "importlib-metadata==8.6.1",
    "iniconfig==2.0.0",
    "jinja2==3.1.5",
    "jmespath==1.0.1",
    "jsonschema==4.23.0",
    "jsonschema-specifications==2024.10.1",
    "lockfile==0.12.2",
    "maison==2.0.0",
    "markdown-it-py==3.0.0",
    "markupsafe==3.0.2",
    "mdurl==0.1.2",
    "molecule==25.2.0",
    "molecule-plugins==23.7.0",
    "mypy-extensions==1.0.0",
    "nodeenv==1.9.1",
    "onigurumacffi==1.4.1",
    "packaging==24.2",
    "parsley==1.3",
    "pathspec==0.12.1",
    "pbr==6.1.1",
    "pexpect==4.9.0",
    "platformdirs==4.3.6",
    "pluggy==1.5.0",
    "pre-commit==4.1.0",
    "ptyprocess==0.7.0",
    "pycparser==2.22",
    "pydantic==2.10.6",
    "pydantic-core==2.27.2",
    "pygments==2.19.1",
    "pyproject-api==1.9.0",
    "pytest==8.3.4",
    "pytest-ansible==25.1.0",
    "pytest-xdist==3.6.1",
    "python-daemon==3.1.2",
    "python-gnupg==0.5.4",
    "pyyaml==6.0.2",
    "referencing==0.36.2",
    "requests==2.32.3",
    "resolvelib==1.0.1",
    "rich==13.9.4",
    "rpds-py==0.22.3",
    "ruamel-yaml==0.18.10",
    "ruyaml==0.91.0",
    "setuptools==75.8.0",
    "subprocess-tee==0.4.2",
    "toml==0.10.2",
    "tox==4.24.1",
    "tox-ansible==25.1.0",
    "typing-extensions==4.12.2",
    "tzdata==2025.1",
    "urllib3==2.3.0",
    "virtualenv==20.29.2",
    "wcmatch==10.0",
    "yamllint==1.35.1",
    "zipp==3.21.0",
]
